### ISSUE TITLE
data augmentation in Class VectorNet

### ISSUE THREAD

**Issue by Gaotttt** [gorkaydemir/FTGN#1]
Thanks for the great work and the repository! 
Could you explain the operation of “data_augmentation" in Class VectorNet, especially the “random_scale”.
Thank you!

**Comment by gorkaydemir** [comment]
Hi,
Thank you for your interest in the work!

In the `augment_tensor` function, we perform two operations on the coordinates of each lane or agent:

- Scale the coordinates by a value `random_scale` sampled from the uniform distribution in the range of [0.75, 1.25]. This scaling is applied to all coordinates of the scene. As the location of the agent of interest is the origin ((0, 0) location), this multiplication simply scales the scene. Note that the last 4 items of lane vectors and the initial 4 items of agent vectors correspond to the coordinate information of input vectors.
- Translate the coordinates by a 2-dimensional vector (`perturbation`) sampled from a Gaussian distribution with a standard deviation of 0.2. This operation randomly shifts the input locations of agents and lanes. Similar to scaling, translation is applied to items corresponding to coordinates in input vectors.

Best
